@startuml
!include style.puml

skinparam {
    classFontSize 13
    classFontStyle bold
    arrowThickness 1.3
    arrowColor #444444
    classBackgroundColor #000000
    classBorderColor MODEL_COLOR
    classArrowColor MODEL_COLOR
}


AddressBook *-down-> "1" UniqueStudentList
AddressBook *-down-> "1" UniqueNameList
AddressBook *-down-> "1" UniqueLessonList
UniqueNameList -[hidden]right- UniqueStudentList
UniqueNameList -[hidden]left- UniqueLessonList

UniqueNameList -right-> "*" Name
UniqueStudentList -right-> Student
UniqueLessonList -down-> Lesson

Student -left-> "1" Name
Lesson -right-> "1" Name

Student *--> Subject
Student *--> Phone
Student *--> Email
Student *--> Address
Student *--> Assignment

Lesson *--> Subject
Lesson *--> Date
Lesson *--> Time

@enduml
