@startuml
!include style.puml
skinparam ArrowFontStyle plain

box "Model" MODEL_COLOR_T1
    participant ":Model" as Model MODEL_COLOR
    participant ":VersionedTutorTrack" as VersionedTutorTrack MODEL_COLOR
end box

[-> Model : undoTutorTrack()
activate Model

Model -> VersionedTutorTrack : undo()
activate VersionedTutorTrack

VersionedTutorTrack -> VersionedTutorTrack : resetData(ReadOnlyTutorTrack)
VersionedTutorTrack --> Model
deactivate VersionedTutorTrack

[<-- Model
deactivate Model

@enduml
