@startuml
!include style.puml
skinparam ArrowFontStyle plain

box "Logic" LOGIC_COLOR_T1
    participant ":LogicManager" as LogicManager LOGIC_COLOR
    participant ":TutorTrackParser" as TutorTrackParser LOGIC_COLOR
    participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box "Model" MODEL_COLOR_T1
    participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> TutorTrackParser : parseCommand("undo")
activate TutorTrackParser

create UndoCommand
TutorTrackParser -> UndoCommand **: create
activate UndoCommand

UndoCommand --> TutorTrackParser
deactivate UndoCommand

TutorTrackParser --> LogicManager : u
deactivate TutorTrackParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoTutorTrack()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand

UndoCommand -[hidden]-> LogicManager
destroy UndoCommand

[<-- LogicManager
deactivate LogicManager
@enduml
